### PR TITLE
update tauri to 1.0.0-rc.6

### PR DESCRIPTION
**Pull request by JonasKruckenberg**

### CODE REVIEW

**Review by FabianLars — APPROVED** [review]

**Comment by JonasKruckenberg** [comment]
I force pushed to get rid of @lucasfernog unsigned commit 😄

**Review by FabianLars — APPROVED** [review]
no idea about that covector stuff but the rest looks good 👍

**Comment by JonasKruckenberg** [comment]
> no idea about that covector stuff but the rest looks good 👍

covector changes are from lucas, but I reviewed them again and they look all good to me

**Comment by lucasfernog** [comment]
I need to setup signing on my VMs, sorry guys :|

**Pull request merged**
